# Generated by Django 3.0.3 on 2020-03-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200303_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='library',
        ),
        migrations.RemoveField(
            model_name='music',
            name='library',
        ),
    ]
