# Generated by Django 3.0.3 on 2020-03-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200303_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
