# Generated by Django 3.0.3 on 2020-03-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200303_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='album',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='name',
        ),
        migrations.AlterField(
            model_name='music',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
