# Generated by Django 3.0.3 on 2020-03-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200303_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
